### PR TITLE
ADD favicon

### PR DESCRIPTION
**Pull request by fastboot**
### What's new ?

This PR adds a new favicon under the public folder.

### CODE REVIEW

**Comment by manonthemat** [comment]
Thanks for the pull request and jumping on the issue.
This is of course very subjective, but I do not see any connection of this favicon with blace.io.
Can you explain to me why you picked this favicon?

**Comment by fastboot** [comment]
> Thanks for the pull request and jumping on the issue. This is of course very subjective, but I do not see any connection of this favicon with blace.io. Can you explain to me why you picked this favicon?

Kept it abstract for now was thinking about something related to marketplace though

**Comment by manonthemat** [comment]
Marking this as accepted for Hacktoberfest purposes, but we won't go with this favicon.
Thanks for the work though.
I'll keep this PR open until Hacktoberfest is over, so you can meet your PR counts.

**Comment by fastboot** [comment]
> Marking this as accepted for Hacktoberfest purposes, but we won't go with this favicon. Thanks for the work though. I'll keep this PR open until Hacktoberfest is over, so you can meet your PR counts.

Hey @manonthemat, that's so nice of you. I apologize for not being able to provide what was expected but I hope I can contribute more to the repository in the future :)

Coming to hacktoberfest, I think we can close this PR without merging the changes I just don't want to contribute for the purpose of participating rather I want to do it in order to learn and help the community. No worries I'll raise another PR for any other issues I find. 

Thanks for letting me work on this really grateful for that. Let me know if I can still contribute in any way possible would be more than happy to do it.

**Pull request closed without merging**
